### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by ispielma** [labscript-suite/lyse#110]
I got the following error when running lyse in python 3.10.13.  The fix is really simple: in line 1106 one needs to change ``status_percent`` to ``int(status_percent)``.  See the actual error below.

I am posting this here as a bug rather than doing a pull request because I don't have a clean fork of lyse setup for this sort of thing.

```
Traceback (most recent call last):
  File "C:\Users\rubidium\AppData\Local\miniconda3\envs\labscript\lib\site-packages\lyse\__main__.py", line 1106, in paint
    progress_bar_option.progress = status_percent # change to int(status_percent)
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by dihm** [comment]
Another victim of the PyQT implicit type casting deprecations. Can you tell me what your pyqt version is? I'd like to reproduce and see if there are any other deprecations I can squash at the same time.

**Comment by ispielma** [comment]
For completeness here are all of the qt related items dumped from ``conda list qt*``:
```
pyqt5                     5.15.10                  pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.13.0                  pypi_0    pypi
pyqtgraph                 0.13.3                   pypi_0    pypi
qtutils                   3.1.0                    pypi_0    pypi
```
