### ISSUE TITLE
Matplotlib 3.2.x Compatability Issue

### ISSUE THREAD

**Issue by zakv** [labscript-suite/lyse#63]
When starting lyse (hg commit d8c69309a825) in an environment with matplotlib 3.2.1 I get the following error:

```python
Traceback (most recent call last):
  File "C:\Users\waveguide3\Desktop\labscript_test_install_3\lyse\analysis_subprocess.py", line 505, in <module>
    lyse.figure_manager.install()
  File "C:\Users\waveguide3\Desktop\labscript_test_install_3\lyse\figure_manager.py", line 139, in install
    raise RuntimeError(message)
RuntimeError: install() must be imported prior to importing pylab/pyplot in order to correctly override the figure() function.
```

In the latest github commit those lines are here https://github.com/labscript-suite/lyse/blob/622b79eb4bff4f7cc784447ce73da78b4d094297/lyse/analysis_subprocess.py#L444 and here https://github.com/labscript-suite/lyse/blob/622b79eb4bff4f7cc784447ce73da78b4d094297/lyse/figure_manager.py#L133

This error doesn't occur with matplotlib 3.1.3. I opened up the debugger and it seems that with matplotlib 3.2.1 `'matplotlib.pyplot' in sys.modules` evaluates to `False` before the call to `import matplotlib` in `analysis_subprocess.py` but it evaluates to `True` right after the import.

One work around may be to put the `import lyse...` block of code before the `import matplotlib...` block of code in `analysis_subprocess.py`. That worked fine with both matplotlib 3.1.3 and 3.2.1, though I haven't tested older versions.

Interestingly lyse also seemed to work just fine with matplotlib 3.2.1 (without the above change) if I simply commented out the line that raises the `RuntimeError`. Admittedly I'm not 100% sure what behavior to look for to ensure that the `FigureManager` monkey patch works. The figure windows aren't brought to the front when new data is plotted if that's relevant.

Sticking with matplotlib 3.1.3 for now is no problem at all; I'm sure you guys have plenty on your plates at the moment with the bitbucket move.

**Comment by philipstarkey** [comment]
Calling `matplotlib.use()` as of matplotlib/matplotlib@208d5e37e1d4961aadc0dec479332d2d0b6fdfc0 now imports pyplot. So the earlier lines in analysis_subprocess.py are now importing something they didn't on previous versions of matplotlib. Haven't investigated the best resolution for this, but at least we know why it's happening!

**Comment by zakv** [comment]
Oh yep, good catch.

The expression `'matplotlib.pyplot' in sys.modules` evaluated to `True` after `import matplotlib` but before the explicit calls to `matplotlib.use()` in `analysis_subprocess.py` when I ran Lyse in a debugger. However if instead I just add some print statements and run it without the debugger, `'matplotlib.pyplot' in sys.modules` doesn't evaluate to `True` until after the explicit call to `matplotlib.use()`. I guess the debugger does some extra things with imports that I didn't know about.

**Comment by chrisjbillington** [comment]
> The expression 'matplotlib.pyplot' in sys.modules evaluated to True after import matplotlib but before the explicit calls to matplotlib.use() in analysis_subprocess.py when I ran Lyse in a debugger.

That's not what I would expect, so yeah suspect the debugger is doing something magic. The behaviour you describe with print statements is what I would expect given the change in matplotlib that @philipstarkey highlighted.

This should be fixed in #65 where we can tell matplotlib via an environment variable which backend to use without importing it.

**Comment by zakv** [comment]
I manually applied the changes from #65 to the bitbucket install on my end and they worked like a charm! Tested it both with matplotlib 3.2.1 and 3.1.3 and had no issues.

**Comment by chrisjbillington** [comment]
Thanks for testing!
